---
version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: voting-app
    ports:
      - 5000:80

  worker:
    image: worker-app

  reuslt:
    image: result-app
    ports:
      - 5001:80

---
version: "3"
services:
  httpd:
    container_name: httpd
    image: httpd:latest
    ports:
    - 8082:80
    volumes:
    - /opt/security:/usr/local/apache2/htdocs
