services:
  portainer:
    image: portainer/portainer-ce:lts
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_PORTAINER}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_PORTAINER}
      - VIRTUAL_PORT=${VIRTUAL_PORT_PORTAINER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_URI=${POSTGRES_HOST}:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=${POSTGRES_SUPERUSER_PASSWORD}
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  portainer_data: