services:
  redis:
    image: redis:alpine

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: voting-app
    ports:
      - 5000:80
    links:
      - redis

  result:
    image: result-app
    ports:
      - 5001:80
    links:
      - db

  worker:
    image: worker-app
    links:
      - redis
      - db